apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/myapp-repo
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/myapp-repo
  newTag: aa68ef2e
- name: 111868661773.dkr.ecr.us-west-2.amazonaws.com/myapp-repo
  newName: 111868661773.dkr.ecr.us-west-2.amazonaws.com/myapp-repo
  newTag: 1de9e520
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
